### ISSUE TITLE
Application Frontend plan

### ISSUE THREAD

**Issue by F1lus** [F1lus/fullstack#1]
# Plan structure
- The plans must be wireframes
- It doesn't have to reflect the final product, but in the end it must be modified so that it does
- Each page of the frontend must be planned
- One photo should only contain one plan
- When the plans are done, leave it in the comments

## The App
The application will be a Twitter/X clone, so our aim is to create something similar to that

## Pages
- **Login screen**
- **Registration screen**
- **Home**: A page where we we can see tweets of other users
- **Profile**: A place where the users can see their own tweets, retweets, etc. One user can access other user's profiles aswell
- **Tweet details**: A detailed page of a selected tweet, all the comments are visible, and adding a comment is also possible here

### Components
There are components which are visible everywhere:
- Navbar: contains a logo, a login/register button when not logged in, a profile button if logged in, and a search bar at the center

**Comment by istokistvan** [comment]
First versions of the wireframes:

- Login page:

![login](https://github.com/F1lus/fullstack/assets/55344429/f3f1f6ee-59db-442c-a258-944b8aaae1ba)

- Register page:

![register](https://github.com/F1lus/fullstack/assets/55344429/86a25df3-0dd6-4f2f-a686-d3c63867463a)

- Home page:

![home](https://github.com/F1lus/fullstack/assets/55344429/4e7bbb4f-c3c2-4aed-b268-a4cabeaae384)

- Tweet:

![tweet](https://github.com/F1lus/fullstack/assets/55344429/6cdb45f9-4935-416e-8ab1-06c60f8a5f44)

- Profile page:

![profile](https://github.com/F1lus/fullstack/assets/55344429/e0a01600-5dd7-4eb1-b0eb-e561da876456)

**Comment by F1lus** [comment]
## Needs fix
I think that the **Username** and **displayname** looks a bit strange on the **Profile**. Since the profile picture is floating on the left, I think it would be a better approach to put it under that, and the center would be reserved for the posts. **The others look good** but I don't think that the profile would provide a good **UX**.

## Improvement
Because the profile has component floating to the left, we need to see how it would look on different screen sizes, since on mobile, the floating would completely break this page.

**Comment by istokistvan** [comment]
So, in your opinion, the profile page would look better this way: 

![image](https://github.com/F1lus/fullstack/assets/55344429/203245a9-f87f-42ef-b477-0cc3156f2e0e)

**Comment by istokistvan** [comment]
First versions of the mobile views: 
- Login page:

![image](https://github.com/F1lus/fullstack/assets/55344429/83bf93d0-b17f-4f5b-b85d-1f7da3f5d2a7)

- Register page: 

![image](https://github.com/F1lus/fullstack/assets/55344429/db9e47de-fe14-41ef-af8c-c4b6a7a94f0b)

- Home page:

![image](https://github.com/F1lus/fullstack/assets/55344429/861c1015-ca13-4545-9421-9809d3cda0e6)

- Profile page:

![image](https://github.com/F1lus/fullstack/assets/55344429/869e614b-b5f3-455c-b514-00930523ec51)

- Tweet details page:

![image](https://github.com/F1lus/fullstack/assets/55344429/dfdccfba-b322-49f4-a4cd-0a92bc306555)

**Comment by F1lus** [comment]
**Good job! Consider it done**
